### ISSUE TITLE
Deprecate that package

### ISSUE THREAD

**Issue by mabar** [wodCZ/nette-dotenv#5]
This feature is natively supported by nette/di bridge to neon since 2011
You can simply call php functions in neon with `::` prefix. So replacement for that package is `::getenv(YOUR_VAR)`
https://doc.nette.org/en/2.4/di-configuration#toc-advanced-syntax
https://github.com/nette/di/commit/e78342ca8ad1a9101956d6fb91f5028218ea69ef

**Comment by vhenzl** [comment]
@mabar No, the feature provided by this package AFAIK isn't supported natively by Nette. 

Purpose of this package is to provide **support for `.env` files**. PHP function `getenv` you are talking about can return only _real_ environment variables. With `@env::get('SOME_VARIABLE')` you can access in a unified way both real environment variables and variables stored in `.env` file.

For more information about `.env` files see eg. https://github.com/vlucas/phpdotenv#why-env

**Comment by mabar** [comment]
ok
